routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('register');
});

Auth::routes();

Route::get('/profil', 'profilController@index')->name('admin/profil');
Route::resource('peserta','PesertaController');
Route::get('/', 'DashboardController@index');

Route::get('/registrasi', 'PesertaController@registrasi');
Route::get('/seleksi', 'SeleksiController@index');
Route::get('/dashboard', 'DashboardController@index');

Route::post('/registrasiPeserta', 'PesertaController@registrasi');
Route::post('image-view','PesertaController@storeImage');
Route::get('/prosesSeleksi', 'SeleksiController@prosesSeleksi');

resources/views/base.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <!-- For Google -->
    <link rel="author" href="https://plus.google.com/+Scoopthemes">
    <link rel="publisher" href="https://plus.google.com/+Scoopthemes">

    <!-- Canonical -->
    <link rel="canonical" href="">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.7/css/fileinput.css" media="all" rel="stylesheet" type="text/css"/>
    <!-- font Awesome CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

    <!-- Main Styles CSS -->
    <link href="/assets/css/main.css" rel="stylesheet"> {{-- ini cara memanggil css dari folder assets -> css --}}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
          margin-bottom: 0;
          border-radius: 0;
        }

        /* Add a gray background color and some padding to the footer */
        footer {
          background-color: #f2f2f2;
          padding: 25px;
        }
        /*inline-block size followd by content*/
        .content
        {
            padding-left : 50px;
            padding-right: 50px;
            padding-bottom : 10px;
            /*display: inline-block; */
        }
        .img
        {
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
        .carousel-inner img
        {
            width: 100%; /* Set width to 100% */
            margin: auto;
            min-height:200px;
        }

        .fileinput-remove,
        .fileinput-upload{
            display: none;
        }

        hr {
                display: block;
                margin-top: 0.5em;
                margin-bottom: 0.5em;
                margin-left: auto;
                margin-right: auto;
                border-style: inset;
                border-width: 2px;
            }

        .input-image{
            align-self: center
            margin:0 auto;
            padding: 20px;
            margin: 20px;
            background-color: #fff;
            box-shadow: 0px 0px 20px #c1c1c1;
        }

        .table{
            text-align: center;
        }


      </style>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" style="background:rgba(0,0,0,0.5);">
        <div class="container-fluid">

          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
        <a class="navbar-brand" href="{{url('/registrasi')}}" style="font-weight:bold;color:black;">Beasiswa Fatamorgana </a>
          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
              <li class="{{ Request::is('registrasi') ? 'active' : '' }}"><a href="{{url('/registrasi')}}">Registrasi</a></li>
              <li class="{{ Request::is('seleksi') ? 'active' : '' }}"><a href="{{url('/seleksi')}}">Seleksi</a></li>
              <li class="{{ Request::is('dashboard') ? 'active' : '' }}"><a href="{{url('/dashboard')}}">Dashboard</a></li>
            </ul>
          </div>
     </div>
</nav><br><br>

    @yield('content') {{-- Semua file konten kita akan ada di bagian ini --}}

</div>

<footer class="container-fluid text-center">
    <p>2019&copy; All Right Reserved</p>
</footer>
<!-- /#wrapper -->

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>

<!-- Bootstrap JavaScript -->
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.7/js/fileinput.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.7/themes/fa/theme.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" type="text/javascript"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" type="text/javascript"></script>
<script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>
 <script type="text/javascript">
        $("#file-1").fileinput({
            theme: 'fa',
            uploadUrl: "/image-view",
            uploadExtraData: function() {
                return {
                    _token: $("input[name='_token']").val(),
                };
            },
            allowedFileExtensions: ['jpg', 'png', 'pdf', 'jpeg', 'docx'],
            overwriteInitial: false,
            maxFileSize: 3000,
            maxFilesNum: 10,
            slugCallback: function (filename) {
                return filename.replace('(', '_').replace(']', '_');
            }
        });
        $("#file-2").fileinput({
            theme: 'fa',
            uploadUrl: "/image-view",
            uploadExtraData: function() {
                return {
                    _token: $("input[name='_token']").val(),
                };
            },
            allowedFileExtensions: ['jpg', 'png', 'pdf', 'jpeg', 'docx'],
            overwriteInitial: false,
            maxFileSize: 3000,
            maxFilesNum: 10,
            slugCallback: function (filename) {
                return filename.replace('(', '_').replace(']', '_');
            }
        });

        $("#file-3").fileinput({
            theme: 'fa',
            uploadUrl: "/image-view",
            uploadExtraData: function() {
                return {
                    _token: $("input[name='_token']").val(),
                };
            },
            allowedFileExtensions: ['jpg', 'png', 'pdf', 'jpeg', 'docx'],
            overwriteInitial: false,
            maxFileSize: 3000,
            maxFilesNum: 4,
            slugCallback: function (filename) {
                return filename.replace('(', '_').replace(']', '_');
            }
        });
    </script>

    <script>
        $(document).ready(function(){
            $("#srcData").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#pesertaTable tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>

<!-- Custom JavaScript -->
<script src="/assets/js/custom.js"></script> {{-- ini cara memanggil js dari folder assets -> js --}}
</body>

</html>

resources/views/dashboard.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard Peserta Beasiswa')

@section('content_header')
    <h1>Dashboard Peserta Beasiswa</h1>
@stop

    @section('content')
    <!-- Main Section -->
    <section class="main-section">
        <!-- Add Your Content Inside -->
        <div class="content">
            <!-- Remove This Before You Start -->
            @if(Session::has('alert-success'))
                <div class="alert alert-success">
                    <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
                </div>
            @endif

            <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-blue">
                      <div class="inner">
                        <h3>{{DB::table('peserta')->count()}}</h3>

                        <p>Jumlah Peserta</p>
                      </div>
                      <div class="icon">
                        <i class="ion ion-person-add"></i>
                      </div>
                    </div>

                  </div>

                  <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-green">
                      <div class="inner">
                        <h3>{{DB::table('result')->max('nilai_topsis')}}</h3>

                        <p>Score Tertinggi</p>
                      </div>
                      <div class="icon">
                            <i class="ion ion-podium"></i>
                          </div>
                    </div>
                  </div>

                  <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-yellow">
                      <div class="inner">
                        <h3>{{DB::table('result')->min('nilai_topsis')}}</h3>

                        <p>Score terendah</p>
                      </div>
                      <div class="icon">
                            <i class="ion ion-podium"></i>
                          </div>
                    </div>
                  </div>

                  <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-red">
                      <div class="inner">
                        <h3><?php echo floatval(DB::table('result')->avg('nilai_topsis')); ?></h3>

                        <p>Score Rata - rata</p>
                      </div>
                      <div class="icon">
                        <i class="ion ion-podium"></i>
                      </div>
                    </div>
                  </div>
            <hr>

            <input class="form-control" id="srcData" type="text" placeholder="Search.."> <br>
            <div class="table-responsive">
            <table class="table table-bordered table-striped" id ="table">
                <thead>
                <tr>
                    <th class="text-center">Peringkat</th>
                    <th class="text-center">Nomor Id Peserta</th>
                    <th class="text-center">Nama</th>
                    <th class="text-center">Institusi</th>
                    <th class="text-center">Nomor induk Mahasiswa</th>
                    <th class="text-center">Score </th>
                    <th class="text-center">Keterangan</th>
                </tr>
                </thead>
                <tbody id = "pesertaTable">
                @foreach($hasil as $key =>$datas)
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{{ $datas->id_peserta }}</td>
                        <td>{{ $datas->nama }}</td>
                        <td>{{ $datas->institusi}}</td>
                        <td>{{ $datas->ni_mhs }}</td>
                        <td>{{ $datas->nilai_topsis }}</td>
                        <td>{{ $datas->Keterangan }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            </div>

            @section('js')
            <script>
              $(function () {
                $('#table').DataTable({
                  'paging'      : true,
                  'lengthChange': false,
                  'searching'   : true,
                  'ordering'    : true,
                  'info'        : true,
                  'autoWidth'   : false
                })
              })
            </script>
            @stop

        </div>
        <!-- /.content -->
    </section>

    <!-- /.main-section -->
@endsection

resources/views/register.blade.php
@extends('adminlte::page')

@section('title', 'Registrasi Peserta')

@section('content_header')
    <h1>Registrasi Peserta</h1>
@stop

    @section('content')
<section class="main-section">
    <div class="container">
            <h2>Pendaftaran Beasiswa S2 Fatamorgana </h2>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form action="{{ url('/registrasiPeserta') }}"  method="POST">
                {{ csrf_field() }}
                <br>
                <div class="panel panel-primary">
                    <div class="panel-heading text-center"><h3>Biodata </h3> </div>
                    <br>
                    <div class="panel-body">
                        <div class="form-group col-md-4">
                            <label for="name">Nama   :</label>
                            <input type="text" class="form-control" id="nama" name = "nama">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="pins">Institusi :</label>
                            <input type="text" class="form-control" id="institusi" name= "institusi">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="pins">Nomor Kartu tanda Mahasiswa</label>
                            <input type="text" class="form-control" id="ktm" name = "ktm">
                        </div>
                    </div>
                </div>
                <br>
                <div class="panel panel-primary text-center">
                <div class="panel-heading text-center"><h3>Score Index Prestasi per semester</h3></div>
                <br>
                    <div class="panel-body">
                        <div class="form-group row">
                            <div class="col-xs-3">
                                <label for="ex1">IP Semester 1</label>
                                <input class="form-control" id="ip1" name ="ip1" type="number" step="0.001">
                            </div>
                            <div class="col-xs-3">
                                <label for="ex2">IP Semester 3</label>
                                <input class="form-control" id="ip3" name ="ip3" type="number" step="0.001">
                            </div>
                            <div class="col-xs-3">
                                <label for="ex3">IP Semester 5</label>
                                <input class="form-control" id="ip5" name ="ip5" type="number" step="0.001">
                            </div>
                            <div class="col-xs-3">
                                    <label for="ex3">IP Semester 7</label>
                                    <input class="form-control" id="ip7" name ="ip7" type="number" step="0.001">
                            </div>
                        </div>
                             <br>
                        <div class="form-group row">
                                <div class="col-xs-3">
                                    <label for="ex1">IP Semester 2</label>
                                    <input class="form-control" id="ip2" name ="ip2" type="number" step="0.001">
                                </div>
                                <div class="col-xs-3">
                                    <label for="ex2">IP Semester 4</label>
                                    <input class="form-control" id="ip4" name ="ip4" type="number" step="0.001">
                                </div>
                                <div class="col-xs-3">
                                    <label for="ex3">IP Semester 6</label>
                                    <input class="form-control" id="ip6" name ="ip6" type="number" step="0.001">
                                </div>
                                <div class="col-xs-3">
                                    <label for="ex3">IP Semester 8</label>
                                    <input class="form-control" id="ip8" name ="ip8" type="number" step="0.001">
                                </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="panel panel-primary">
                <div class="panel-heading text-center"><h3>Keaktifan </h3></div>
                <br>
                    <div class="panel-body">
                        <div class="form-group col-md-6">
                            <label for="pins">Jumlah pengalaman  :</label>
                            <input class="form-control" type="number" id="pengalaman" name ="pengalaman">
                            <div class="text-center">
                                <div class="row">
                                    <div class="col-lg-8 col-sm-12 col-11 input-image">
                                        <h2 class="text-center text-danger">Upload Setifikat pengalaman</h2><br>
                                        {!! csrf_field() !!}
                                        <div class="form-group">
                                            <div class="file-loading">
                                                <input id="file-1" type="file" name="file" multiple class="file" data-overwrite-initial="false" data-min-file-count="1">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="pins">Jumlah Penghargaan :</label>
                            <input  class="form-control" type="number" id="penghargaan" name ="penghargaan" >
                            <div class="text-center">
                                <div class="row">
                                    <div class="col-lg-8 col-sm-12 col-11 input-image">
                                        <h2 class="text-center text-danger">Upload Setifikat Penghargaan</h2><br>
                                            {!! csrf_field() !!}
                                        <div class="form-group">
                                            <div class="file-loading">
                                                <input id="file-2" type="file" name="file" multiple class="file" data-overwrite-initial="false" data-min-file-count="1">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="panel panel-primary text-center">
                <div class="panel-heading text-center"><h3>Score Bahasa Asing</h3></div>
                <br>
                    <div class ="panel-body">
                        <div class="form-group row">
                            <div class="col-xs-6">
                                <label for="ex1">Score TOEFL ITP</label>
                                <input class="form-control"  id="teofl_itp" name ="toefl_itp" type="number">
                            </div>
                            <div class="col-xs-6">
                                <label for="ex2">Score IELTS</label>
                                <input class="form-control" id="ielts" name ="ielts" type="number">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-xs-6">
                                <label for="ex3">Score TOEFL Ibt</label>
                                <input class="form-control" id="teofl_ibt" name ="toefl_ibt" type="number">
                            </div>
                            <div class="col-xs-6">
                                    <label for="ex3">Score TOEIC</label>
                                    <input class="form-control" id="toeic" name = "toeic" type="number">
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <br>
                <div class="container text-center">
                        <button type="submit" class="btn-lg btn-md btn-primary">Daftar</button>
                        <button type="reset" class="btn-lg btn-md btn-danger">Reset</button>
                </div>
            </form>
            <br>
            <br>
    </div>
</section>
@endsection

resources/views/selection.blade.php
@extends('adminlte::page')

@section('title', 'Proses Seleksi')

@section('content_header')
    <h1>Proses Seleksi</h1>
@stop

@section('content')
    <!-- Main Section -->
    <section class="main-section">
        <!-- Add Your Content Inside -->
        <div class="content">
            <!-- Remove This Before You Start -->
            <h1>List Peserta</h1>
            @if(Session::has('alert-success'))
                <div class="alert alert-success">
                    <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
                </div>
            @endif
            <hr>
            <input class="form-control" id="srcData" type="text" placeholder="Search.."> <br>
            <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th class="text-center">Nomor Id</th>
                    <th class="text-center">Nama</th>
                    <th class="text-center">Institusi</th>
                    <th class="text-center">Nomor induk Mahasiswa</th>
                    <th class="text-center">IP semester 1</th>
                    <th class="text-center">IP semester 2</th>
                    <th class="text-center">IP semester 3</th>
                    <th class="text-center">IP semester 4</th>
                    <th class="text-center">IP semester 5</th>
                    <th class="text-center">IP semester 6</th>
                    <th class="text-center">IP semester 7</th>
                    <th class="text-center">IP semester 8</th>
                    <th class="text-center">Jumlah Organisasi atau Pengalaman</th>
                    <th class="text-center">Jumlah Penghargaan</th>
                    <th class="text-center">TOEFL ITP</th>
                    <th class="text-center">TOEFL IBT</th>
                    <th class="text-center">IELTES</th>
                    <th class="text-center">TOEIC</th>
                </tr>
                </thead>
                <tbody id = "pesertaTable">
                @foreach($peserta as $datas)
                    <tr>
                        <td>{{ $datas->id }}</td>
                        <td>{{ $datas->nama }}</td>
                        <td>{{ $datas->institusi }}</td>
                        <td>{{ $datas->ni_mhs}}</td>
                        <td>{{ $datas->ip_1 }}</td>
                        <td>{{ $datas->ip_2 }}</td>
                        <td>{{ $datas->ip_3 }}</td>
                        <td>{{ $datas->ip_4}}</td>
                        <td>{{ $datas->ip_5 }}</td>
                        <td>{{ $datas->ip_6 }}</td>
                        <td>{{ $datas->ip_7 }}</td>
                        <td>{{ $datas->ip_8}}</td>
                        <td>{{ $datas->keaktifan }}</td>
                        <td>{{ $datas->penghargaan}}</td>
                        <td>{{ $datas->toefel_itp}}</td>
                        <td>{{ $datas->toefel_ibt}}</td>
                        <td>{{ $datas->ielts}}</td>
                        <td>{{ $datas->toeic}}</td>
                        <td>
                            <form action="{{ route('peserta.destroy', $datas->id) }}" method="post">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                                <a href="{{ route('peserta.edit',$datas->id) }}" class=" btn btn-sm btn-primary">Edit</a>
                                <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <br>
            <br>
            </div>
            <a  class="btn btn-primary btn-lg btn-block" href="{{action('SeleksiController@prosesSeleksi')}}" role = "button">Lakukan Proses Seleksi</a>
        </div>
        <!-- /.content -->
    </section>
    <!-- /.main-section -->
@endsection